// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _4_Calculator.Data;

#nullable disable

namespace _4_Calculator.Migrations
{
    [DbContext(typeof(CalculatorContext))]
    partial class CalculatorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("_4_Calculator.Data.DataImputVariant", b =>
                {
                    b.Property<int>("ID_DataInputVariant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_DataInputVariant"));

                    b.Property<string>("Operand_1")
                        .HasColumnType("carchar(128)");

                    b.Property<string>("Operand_2")
                        .HasColumnType("carchar(128)");

                    b.Property<string>("Type_operation")
                        .HasColumnType("carchar(128)");

                    b.HasKey("ID_DataInputVariant");

                    b.ToTable("DataImputVariants");
                });
#pragma warning restore 612, 618
        }
    }
}
